//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chinookEntities : DbContext
    {
        public chinookEntities()
            : base("name=chinookEntities")
        {
        }
        
        public chinookEntities(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<album> albums { get; set; }
        public virtual DbSet<artist> artists { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<invoice_items> invoice_items { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<media_types> media_types { get; set; }
        public virtual DbSet<playlist> playlists { get; set; }
        public virtual DbSet<track> tracks { get; set; }
    }
}
