//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class track
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public track()
        {
            this.invoice_items = new HashSet<invoice_items>();
            this.playlists = new HashSet<playlist>();
        }
    
        public long TrackId { get; set; }
        public string Name { get; set; }
        public Nullable<long> AlbumId { get; set; }
        public long MediaTypeId { get; set; }
        public Nullable<long> GenreId { get; set; }
        public string Composer { get; set; }
        public long Milliseconds { get; set; }
        public Nullable<long> Bytes { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual album album { get; set; }
        public virtual genre genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_items> invoice_items { get; set; }
        public virtual media_types media_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<playlist> playlists { get; set; }
    }
}
