//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVA.Infrastructure.Dictionaries
{
	public interface ICommonViewDictionary : IViewModelDictionary
	{
        [Translatable]
		string YesNoMessageCaption
		{
            get; set;
		}
        [Translatable]
		string UnavailableButton
		{
            get; set;
		}
        [Translatable]
		string NotDefined
		{
            get; set;
		}
        [Translatable]
		string ProgramName
		{
            get; set;
		}
        [Translatable]
		string PreDeleteMessage
		{
            get; set;
		}
        [Translatable]
		string PreCloseViewMessage
		{
            get; set;
		}
	}	
}
