//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVA.Infrastructure.Dictionaries
{
	public interface IEpisodePropertiesViewDictionary : IViewModelDictionary
	{
        [Translatable]
		string TeamNotChoseException
		{
            get; set;
		}
        [Translatable]
		string NameLabel
		{
            get; set;
		}
        [Translatable]
		string TeamLabel
		{
            get; set;
		}
        [Translatable]
		string SecondTeamLabel
		{
            get; set;
		}
        [Translatable]
		string MatchDateLabel
		{
            get; set;
		}
        [Translatable]
		string PlayersLabel
		{
            get; set;
		}
        [Translatable]
		string NotesLabel
		{
            get; set;
		}
        [Translatable]
		string EpisodeStartLabel
		{
            get; set;
		}
        [Translatable]
		string EpisodeEndLabel
		{
            get; set;
		}
        [Translatable]
		string SaveButton
		{
            get; set;
		}
        [Translatable]
		string CancelButton
		{
            get; set;
		}
        [Translatable]
		string CreatingEpisodeErrorCaption
		{
            get; set;
		}
        [Translatable]
		string IncorrectEpisodeNameError
		{
            get; set;
		}
	}	
}
