//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVA.Infrastructure.Dictionaries
{
	public interface IExportGroupViewDictionary : IViewModelDictionary
	{
        [Translatable]
		string NameLabel
		{
            get; set;
		}
        [Translatable]
		string LocationLabel
		{
            get; set;
		}
        [Translatable]
		string ExportButton
		{
            get; set;
		}
        [Translatable]
		string ViewButton
		{
            get; set;
		}
        [Translatable]
		string DeleteButton
		{
            get; set;
		}
        [Translatable]
		string ContextMenuMoveUp
		{
            get; set;
		}
        [Translatable]
		string ContextMenuMoveDown
		{
            get; set;
		}
        [Translatable]
		string EnterNameWatermark
		{
            get; set;
		}
        [Translatable]
		string EnterLocationWatermark
		{
            get; set;
		}
        [Translatable]
		string GridColumnName
		{
            get; set;
		}
        [Translatable]
		string GridColumnPlayers
		{
            get; set;
		}
        [Translatable]
		string GridColumnProperties
		{
            get; set;
		}
        [Translatable]
		string GridColumnNotes
		{
            get; set;
		}
        [Translatable]
		string InvalidGroupNameException
		{
            get; set;
		}
	}	
}
