//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVA.Infrastructure.Dictionaries
{
	public interface IExportViewDictionary : IViewModelDictionary
	{
        [Translatable]
		string GridColumnName
		{
            get; set;
		}
        [Translatable]
		string GridColumnProgress
		{
            get; set;
		}
        [Translatable]
		string OpenInFolderButton
		{
            get; set;
		}
        [Translatable]
		string GridColumnExportTime
		{
            get; set;
		}
        [Translatable]
		string EpisodesInGroup
		{
            get; set;
		}
        [Translatable]
		string GridColumnNotes
		{
            get; set;
		}
        [Translatable]
		string Canceled
		{
            get; set;
		}
        [Translatable]
		string StartExportButton
		{
            get; set;
		}
        [Translatable]
		string CancelExportButton
		{
            get; set;
		}
	}	
}
