//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVA.Infrastructure.Dictionaries
{
	public interface ILicenseViewDictionary : IViewModelDictionary
	{
        [Translatable]
		string LicenseTb
		{
            get; set;
		}
        [Translatable]
		string RequestLicenseBtn
		{
            get; set;
		}
        [Translatable]
		string RequestLicenseMessage
		{
            get; set;
		}
        [Translatable]
		string PublicKeyTb
		{
            get; set;
		}
        [Translatable]
		string ApplyBtn
		{
            get; set;
		}
	}	
}
