//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVA.Infrastructure.Dictionaries
{
	public interface IMainControlViewDictionary : IViewModelDictionary
	{
        [Translatable]
		string ActionsMenuItem
		{
            get; set;
		}
        [Translatable]
		string VideoAnalyzeButton
		{
            get; set;
		}
        [Translatable]
		string SettingsButton
		{
            get; set;
		}
        [Translatable]
		string AboutButton
		{
            get; set;
		}
        [Translatable]
		string LicenseButton
		{
            get; set;
		}
        [Translatable]
		string SearchEpisodesButton
		{
            get; set;
		}
        [Translatable]
		string CatalogsButton
		{
            get; set;
		}
        [Translatable]
		string TeamsButton
		{
            get; set;
		}
        [Translatable]
		string PlayersButton
		{
            get; set;
		}
        [Translatable]
		string TemplatesButton
		{
            get; set;
		}
        [Translatable]
		string ExportButton
		{
            get; set;
		}
        [Translatable]
		string UpdateToLatesButton
		{
            get; set;
		}
        [Translatable]
		string UpdateToStableButton
		{
            get; set;
		}
        [Translatable]
		string TranslationsButton
		{
            get; set;
		}
        [Translatable]
		string MessagesExpander
		{
            get; set;
		}
        [Translatable]
		string NavigationExpander
		{
            get; set;
		}
        [Translatable]
		string ClearMessageListButton
		{
            get; set;
		}
	}	
}
