//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVA.Infrastructure.Dictionaries
{
	public interface IPlayerCollectionDictionary : IViewModelDictionary
	{
        [Translatable]
		string CreatePlayerButton
		{
            get; set;
		}
        [Translatable]
		string GridColumnName
		{
            get; set;
		}
        [Translatable]
		string NewPlayerName
		{
            get; set;
		}
        [Translatable]
		string DeleteSelectedPlayers
		{
            get; set;
		}
	}	
}
