//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVA.Infrastructure.Dictionaries
{
	public interface IPlayerViewDictionary : IViewModelDictionary
	{
        [Translatable]
		string PlayerNameLabel
		{
            get; set;
		}
        [Translatable]
		string AddContractButton
		{
            get; set;
		}
        [Translatable]
		string SaveButton
		{
            get; set;
		}
        [Translatable]
		string PlayerEpisodesButton
		{
            get; set;
		}
        [Translatable]
		string CurrentContractLabel
		{
            get; set;
		}
        [Translatable]
		string TeamLabel
		{
            get; set;
		}
        [Translatable]
		string NumberLabel
		{
            get; set;
		}
        [Translatable]
		string ContractBeginLabel
		{
            get; set;
		}
        [Translatable]
		string ContractEndLabel
		{
            get; set;
		}
        [Translatable]
		string ContractsTableTitle
		{
            get; set;
		}
        [Translatable]
		string GridColumnTeam
		{
            get; set;
		}
        [Translatable]
		string GridColumnNumber
		{
            get; set;
		}
        [Translatable]
		string EnterPlayerName
		{
            get; set;
		}
        [Translatable]
		string GridColumnContractBegin
		{
            get; set;
		}
        [Translatable]
		string GridColumnContractEnd
		{
            get; set;
		}
        [Translatable]
		string RemoveContractButton
		{
            get; set;
		}
        [Translatable]
		string ChooseTeamWatermark
		{
            get; set;
		}
	}	
}
