//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVA.Infrastructure.Dictionaries
{
	public interface ISearchEpisodesViewDictionary : IViewModelDictionary
	{
        [Translatable]
		string MessageBeforeDelete
		{
            get; set;
		}
        [Translatable]
		string TeamLabel
		{
            get; set;
		}
        [Translatable]
		string PlayersLabel
		{
            get; set;
		}
        [Translatable]
		string PropertiesLabel
		{
            get; set;
		}
        [Translatable]
		string NotesLabel
		{
            get; set;
		}
        [Translatable]
		string RefreshButton
		{
            get; set;
		}
        [Translatable]
		string DeleteButton
		{
            get; set;
		}
        [Translatable]
		string ViewButton
		{
            get; set;
		}
        [Translatable]
		string ExportButton
		{
            get; set;
		}
        [Translatable]
		string MatchDateBeginLabel
		{
            get; set;
		}
        [Translatable]
		string MatchDateEndLabel
		{
            get; set;
		}
        [Translatable]
		string CreateDateBeginLabel
		{
            get; set;
		}
        [Translatable]
		string CreateDateEndLabel
		{
            get; set;
		}
        [Translatable]
		string GribColumnName
		{
            get; set;
		}
        [Translatable]
		string GribColumnTeam
		{
            get; set;
		}
        [Translatable]
		string GribColumnPlayers
		{
            get; set;
		}
        [Translatable]
		string GribColumnProperties
		{
            get; set;
		}
        [Translatable]
		string GribColumnMatchDate
		{
            get; set;
		}
        [Translatable]
		string GribColumnCreateDate
		{
            get; set;
		}
        [Translatable]
		string GribColumnStartTime
		{
            get; set;
		}
        [Translatable]
		string GribColumnSecondTeam
		{
            get; set;
		}
        [Translatable]
		string SetLocationOfSelectedEpisodes
		{
            get; set;
		}
        [Translatable]
		string ChoosePlayersWatermark
		{
            get; set;
		}
        [Translatable]
		string ChoosePropertiesWatermark
		{
            get; set;
		}
        [Translatable]
		string GribColumnEndTime
		{
            get; set;
		}
        [Translatable]
		string GribColumnNotes
		{
            get; set;
		}
        [Translatable]
		string VideoNotFound
		{
            get; set;
		}
        [Translatable]
		string IncorrectMatchDates
		{
            get; set;
		}
        [Translatable]
		string IncorrectCreateDates
		{
            get; set;
		}
	}	
}
