//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVA.Infrastructure.Dictionaries
{
	public interface ISettingsViewDictionary : IViewModelDictionary
	{
        [Translatable]
		string CompressionLevelTb
		{
            get; set;
		}
        [Translatable]
		string Rollback1Tb
		{
            get; set;
		}
        [Translatable]
		string Rollback2Tb
		{
            get; set;
		}
        [Translatable]
		string BaseVideoFolderTb
		{
            get; set;
		}
        [Translatable]
		string CurrentTemplateTb
		{
            get; set;
		}
        [Translatable]
		string YoutubePlaylistTb
		{
            get; set;
		}
        [Translatable]
		string SetToDefaultsBtn
		{
            get; set;
		}
        [Translatable]
		string ApplyBtn
		{
            get; set;
		}
        [Translatable]
		string CancelBtn
		{
            get; set;
		}
        [Translatable]
		string SetFolderToolTip
		{
            get; set;
		}
        [Translatable]
		string ImmediateOpenCreatedEpisodeCb
		{
            get; set;
		}
        [Translatable]
		string EpisodesFolderTb
		{
            get; set;
		}
	}	
}
