//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVA.Infrastructure.Dictionaries
{
	public interface ITeamViewDictionary : IViewModelDictionary
	{
        [Translatable]
		string TeamLabel
		{
            get; set;
		}
        [Translatable]
		string SetLogoButton
		{
            get; set;
		}
        [Translatable]
		string AddContractButton
		{
            get; set;
		}
        [Translatable]
		string SaveButton
		{
            get; set;
		}
        [Translatable]
		string TeamEpisodesButton
		{
            get; set;
		}
        [Translatable]
		string CurrentGridTitle
		{
            get; set;
		}
        [Translatable]
		string GridColumnPlayer
		{
            get; set;
		}
        [Translatable]
		string GridColumnNumber
		{
            get; set;
		}
        [Translatable]
		string GridColumnContractBegin
		{
            get; set;
		}
        [Translatable]
		string GridColumnContractEnd
		{
            get; set;
		}
        [Translatable]
		string ChosePlayerWatermark
		{
            get; set;
		}
        [Translatable]
		string EnterTeamName
		{
            get; set;
		}
        [Translatable]
		string HistoryGridTitle
		{
            get; set;
		}
        [Translatable]
		string RemoveContractButton
		{
            get; set;
		}
	}	
}
