//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVA.Infrastructure.Dictionaries
{
	public interface ITemplatesViewDictionary : IViewModelDictionary
	{
        [Translatable]
		string TemplateNameLabel
		{
            get; set;
		}
        [Translatable]
		string AddNewPropertyButton
		{
            get; set;
		}
        [Translatable]
		string SaveButton
		{
            get; set;
		}
        [Translatable]
		string EnterTemplateNameWatermark
		{
            get; set;
		}
        [Translatable]
		string AddChildProperty
		{
            get; set;
		}
        [Translatable]
		string RemoveProperty
		{
            get; set;
		}
        [Translatable]
		string NewPropertyName
		{
            get; set;
		}
	}	
}
