//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVA.Infrastructure.Dictionaries
{
	public interface IValidationDictionary : IViewModelDictionary
	{
        [Translatable]
		string PlayerNumberMessage
		{
            get; set;
		}
        [Translatable]
		string ContractTeamMessage
		{
            get; set;
		}
        [Translatable]
		string ContractPlayerMessage
		{
            get; set;
		}
        [Translatable]
		string ErrorInCreatingMessage
		{
            get; set;
		}
        [Translatable]
		string ErrorInUpdatingMessage
		{
            get; set;
		}
        [Translatable]
		string ValidationErrorMessage
		{
            get; set;
		}
        [Translatable]
		string PlayerNameMessage
		{
            get; set;
		}
        [Translatable]
		string TeamNameMessage
		{
            get; set;
		}
	}	
}
