//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVA.Infrastructure.Dictionaries
{
	public interface IVideoAnalyzeViewDictionary : IViewModelDictionary
	{
        [Translatable]
		string GridColumnName
		{
            get; set;
		}
        [Translatable]
		string GridColumnTeam
		{
            get; set;
		}
        [Translatable]
		string GridColumnBegin
		{
            get; set;
		}
        [Translatable]
		string GridColumnEnd
		{
            get; set;
		}
        [Translatable]
		string MatchDateLabel
		{
            get; set;
		}
        [Translatable]
		string EpisodeStartLabel
		{
            get; set;
		}
        [Translatable]
		string EpisodeEndLabel
		{
            get; set;
		}
        [Translatable]
		string ChooseTeamWatermark
		{
            get; set;
		}
        [Translatable]
		string GraphicExpander
		{
            get; set;
		}
        [Translatable]
		string TurnOnEditingBtn
		{
            get; set;
		}
        [Translatable]
		string TurnOffEditingBtn
		{
            get; set;
		}
        [Translatable]
		string PenCololLbl
		{
            get; set;
		}
        [Translatable]
		string DisableEditingModeException
		{
            get; set;
		}
        [Translatable]
		string EpisodesListExpander
		{
            get; set;
		}
        [Translatable]
		string MatchPropertiesExpander
		{
            get; set;
		}
        [Translatable]
		string PlaylistColumn
		{
            get; set;
		}
        [Translatable]
		string PenWidth
		{
            get; set;
		}
        [Translatable]
		string ActionAvailableOnlyInAnalyzeModeException
		{
            get; set;
		}
        [Translatable]
		string DrawCircleBtn
		{
            get; set;
		}
        [Translatable]
		string DrawRectangleBtn
		{
            get; set;
		}
        [Translatable]
		string DrawLineBtn
		{
            get; set;
		}
        [Translatable]
		string PlayAllBtn
		{
            get; set;
		}
	}	
}
